version: "3.1"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8000:8000
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
